walker:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  
  # Position Controllers ---------------------------------------
  head_j1_position_controller:
    type: effort_controllers/JointEffortController
    joint: head_j1

  head_j2_position_controller:
    type: effort_controllers/JointEffortController
    joint: head_j2

  right_limb_j1_position_controller:
    type: effort_controllers/JointEffortController
    joint: right_limb_j1

  right_limb_j2_position_controller:
    type: effort_controllers/JointEffortController
    joint: right_limb_j2

  right_limb_j3_position_controller:
    type: effort_controllers/JointEffortController
    joint: right_limb_j3

  right_limb_j4_position_controller:
    type: effort_controllers/JointEffortController
    joint: right_limb_j4

  right_limb_j5_position_controller:
    type: effort_controllers/JointEffortController
    joint: right_limb_j5

  right_limb_j6_position_controller:
    type: effort_controllers/JointEffortController
    joint: right_limb_j6

  right_limb_j7_position_controller:
    type: effort_controllers/JointEffortController
    joint: right_limb_j7

  right_thumb_j1_position_controller:
    type: effort_controllers/JointEffortController
    joint: right_thumb_j1

  right_index_j1_position_controller:
    type: effort_controllers/JointEffortController
    joint: right_index_j1

  right_middle_j1_position_controller:
    type: effort_controllers/JointEffortController
    joint: right_middle_j1

  right_ring_j1_position_controller:
    type: effort_controllers/JointEffortController
    joint: right_ring_j1

  left_limb_j1_position_controller:
    type: effort_controllers/JointEffortController
    joint: left_limb_j1

  left_limb_j2_position_controller:
    type: effort_controllers/JointEffortController
    joint: left_limb_j2

  left_limb_j3_position_controller:
    type: effort_controllers/JointEffortController
    joint: left_limb_j3

  left_limb_j4_position_controller:
    type: effort_controllers/JointEffortController
    joint: left_limb_j4

  left_limb_j5_position_controller:
    type: effort_controllers/JointEffortController
    joint: left_limb_j5

  left_limb_j6_position_controller:
    type: effort_controllers/JointEffortController
    joint: left_limb_j6

  left_limb_j7_position_controller:
    type: effort_controllers/JointEffortController
    joint: left_limb_j7

  left_thumb_j1_position_controller:
    type: effort_controllers/JointEffortController
    joint: left_thumb_j1

  left_index_j1_position_controller:
    type: effort_controllers/JointEffortController
    joint: left_index_j1

  left_middle_j1_position_controller:
    type: effort_controllers/JointEffortController
    joint: left_middle_j1

  left_ring_j1_position_controller:
    type: effort_controllers/JointEffortController
    joint: left_ring_j1

	right_leg_j1_position_controller:
    type: effort_controllers/JointEffortController
    joint: right_leg_j1

  right_leg_j2_position_controller:
    type: effort_controllers/JointEffortController
    joint: right_leg_j2

  right_leg_j3_position_controller:
    type: effort_controllers/JointEffortController
    joint: right_leg_j3

  right_leg_j4_position_controller:
    type: effort_controllers/JointEffortController
    joint: right_leg_j4

  right_leg_j5_position_controller:
    type: effort_controllers/JointEffortController
    joint: right_leg_j5

  right_leg_j6_position_controller:
    type: effort_controllers/JointEffortController
    joint: right_leg_j6

	left_leg_j1_position_controller:
    type: effort_controllers/JointEffortController
    joint: left_leg_j1

  left_leg_j2_position_controller:
    type: effort_controllers/JointEffortController
    joint: left_leg_j2

  left_leg_j3_position_controller:
    type: effort_controllers/JointEffortController
    joint: left_leg_j3

  left_leg_j4_position_controller:
    type: effort_controllers/JointEffortController
    joint: left_leg_j4

  left_leg_j5_position_controller:
    type: effort_controllers/JointEffortController
    joint: left_leg_j5

  left_leg_j6_position_controller:
    type: effort_controllers/JointEffortController
    joint: left_leg_j6
