walker:
# Position Controllers ---------------------------------------
  head_position_controller:
    type: position_controllers/JointTrajectoryController 
    joints: 
      - head_j1
      - head_j2
  right_limb_position_controller:
    type: position_controllers/JointTrajectoryController 
    joints: 
     - right_limb_j1
     - right_limb_j2
     - right_limb_j3
     - right_limb_j4
     - right_limb_j5
     - right_limb_j6
     - right_limb_j7
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      right_limb_j1: {trajectory: 0.1, goal: .0.1}
      right_limb_j2: {trajectory: 0.1, goal: 0.1}
      right_limb_j3: {trajectory: 0.1, goal: 0.1}
      right_limb_j4: {trajectory: 0.1, goal: 0.1}
      right_limb_j5: {trajectory: 0.1, goal: 0.1}
      right_limb_j6: {trajectory: 0.1, goal: 0.1}
      right_limb_j7: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10

  right_thumb_j1_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_thumb_j1
    pid: {p: 1.0, i: 0, d: 0}

  right_index_j1_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_index_j1
    pid: {p: 1.0, i: 0, d: 0}

  right_middle_j1_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_middle_j1
    pid: {p: 1.0, i: 0, d: 0}

  right_ring_j1_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_ring_j1
    pid: {p: 1.0, i: 0, d: 0}

  left_limb_position_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - left_limb_j1
      - left_limb_j2
      - left_limb_j3
      - left_limb_j4
      - left_limb_j5
      - left_limb_j6
      - left_limb_j7
    constraints:
       goal_time: 4.0
       stopped_velocity_tolerance: 1.0
       left_limb_j1: {trajectory: 1.0, goal: 0.5}
       left_limb_j2: {trajectory: 1.0, goal: 0.5}
       left_limb_j3: {trajectory: 1.0, goal: 0.5}
       left_limb_j4: {trajectory: 1.0, goal: 0.5}
       left_limb_j5: {trajectory: 1.0, goal: 0.5}
       left_limb_j6: {trajectory: 1.0, goal: 0.5}
       left_limb_j7: {trajectory: 1.0, goal: 0.5}
    stop_trajectory_duration: 1.0
    state_publish_rate:  50
    action_monitor_rate: 10

  left_thumb_j1_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_thumb_j1
    pid: {p: 1.0, i: 0, d: 0}

  left_index_j1_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_index_j1
    pid: {p: 1.0, i: 0, d: 0}

  left_middle_j1_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_middle_j1
    pid: {p: 1.0, i: 0, d: 0}

  left_ring_j1_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_ring_j1
    pid: {p: 1.0, i: 0, d: 0}

  right_leg_position_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - right_leg_j1
      - right_leg_j2
      - right_leg_j3
      - right_leg_j4
      - right_leg_j5
      - right_leg_j6

  left_leg_position_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - left_leg_j1
      - left_leg_j2
      - left_leg_j3
      - left_leg_j4
      - left_leg_j5
      - left_leg_j6

